import { ArrowUpRight } from 'lucide-react';
import Link from 'next/link';

// TODO: Have legal counsel and the restaurant validate this placeholder policy before production publication.
const restaurantContact = 'nomaderestaubar@gmail.com · 07 45 26 28 23';

const copy = {
  fr: { title:'Politique de confidentialité', back:'Retour au site', intro:'NOMADE attache une grande importance à la protection de vos données personnelles et s’engage à les traiter conformément au Règlement Général sur la Protection des Données (RGPD).', s1:'Données collectées',s1p:'Nous collectons uniquement les données que vous nous transmettez volontairement via le formulaire de contact ou par e-mail : nom, adresse e-mail, numéro de téléphone, contenu de votre message.',s2:'Finalités du traitement',s2p:'Ces données sont utilisées exclusivement pour répondre à vos demandes de réservation, d’information ou de contact. Elles ne sont ni revendues, ni cédées à des tiers.',s3:'Durée de conservation',s3p:'Vos données sont conservées le temps nécessaire au traitement de votre demande, puis supprimées, sauf obligation légale de conservation plus longue.',s4:'Cookies',s4p:'Ce site peut utiliser des cookies de mesure d’audience et, le cas échéant, des cookies tiers (réseaux sociaux, cartes). Vous pouvez à tout moment accepter, refuser ou modifier votre choix via le bandeau de consentement.',s5:'Vos droits',s5p:'Conformément au RGPD, vous disposez d’un droit d’accès, de rectification, d’effacement et de portabilité de vos données, ainsi que d’un droit d’opposition. Pour exercer ces droits, contactez-nous à l’adresse ci-dessous.',s6:'Réclamation',s6p:'Vous pouvez également introduire une réclamation auprès de la CNIL (www.cnil.fr) si vous estimez que vos droits ne sont pas respectés.',contact:'Contact',contactP:'contact@nomade-foix.fr · 05 54 56 63 48'},
  en: { title:'Privacy policy', back:'Back to site', intro:'NOMADE takes the protection of your personal data seriously and processes it in accordance with the General Data Protection Regulation (GDPR).', s1:'Data we collect',s1p:'We only collect data you voluntarily provide via the contact form or by email: name, email address, phone number, and message content.',s2:'Purpose of processing',s2p:'This data is used solely to respond to your booking, information or contact requests. It is never sold or shared with third parties.',s3:'Retention period',s3p:'Your data is kept for as long as necessary to process your request, then deleted, unless a longer legal retention period applies.',s4:'Cookies',s4p:'This site may use audience-measurement cookies and, where applicable, third-party cookies (social media, maps). You can accept, refuse or change your choice at any time via the consent banner.',s5:'Your rights',s5p:'Under the GDPR, you have the right to access, rectify, erase and port your data, as well as a right to object. To exercise these rights, contact us at the address below.',s6:'Complaints',s6p:'You may also lodge a complaint with the CNIL (www.cnil.fr) if you believe your rights are not being respected.',contact:'Contact',contactP:'contact@nomade-foix.fr · 05 54 56 63 48'},
  es: { title:'Política de privacidad', back:'Volver al sitio', intro:'NOMADE concede gran importancia a la protección de sus datos personales y se compromete a tratarlos conforme al Reglamento General de Protección de Datos (RGPD).', s1:'Datos recopilados',s1p:'Solo recopilamos los datos que usted nos facilita voluntariamente a través del formulario de contacto o por correo electrónico: nombre, correo electrónico, teléfono y contenido del mensaje.',s2:'Finalidad del tratamiento',s2p:'Estos datos se utilizan exclusivamente para responder a sus solicitudes de reserva, información o contacto. No se venden ni se ceden a terceros.',s3:'Plazo de conservación',s3p:'Sus datos se conservan durante el tiempo necesario para tramitar su solicitud y después se eliminan, salvo obligación legal de conservación más prolongada.',s4:'Cookies',s4p:'Este sitio puede utilizar cookies de medición de audiencia y, en su caso, cookies de terceros (redes sociales, mapas). Puede aceptar, rechazar o modificar su elección en cualquier momento a través del banner de consentimiento.',s5:'Sus derechos',s5p:'Conforme al RGPD, usted tiene derecho de acceso, rectificación, supresión y portabilidad de sus datos, así como derecho de oposición. Para ejercerlos, contáctenos en la dirección indicada.',s6:'Reclamaciones',s6p:'También puede presentar una reclamación ante la CNIL (www.cnil.fr) si considera que no se respetan sus derechos.',contact:'Contacto',contactP:'contact@nomade-foix.fr · 05 54 56 63 48'}
};

export default async function Confidentialite({ params }: { params: Promise<{ lang: string }> }) {
  const { lang: rawLang } = await params;
  const lang = (['fr', 'en', 'es'] as const).includes(rawLang as 'fr' | 'en' | 'es') ? rawLang as 'fr' | 'en' | 'es' : 'fr';
  const t = { ...copy[lang], contactP: restaurantContact };

  return <main className="legalPage" lang={lang}><div className="legalHead"><p className="eyebrow">NOMADE</p><h1>{t.title}</h1><Link className="textLink" href={`/${lang}#top`}>{t.back} <ArrowUpRight size={16} /></Link></div>
    <p className="lead legalIntro">{t.intro}</p>
    <section className="legalSection"><h2>{t.s1}</h2><p>{t.s1p}</p></section><section className="legalSection"><h2>{t.s2}</h2><p>{t.s2p}</p></section><section className="legalSection"><h2>{t.s3}</h2><p>{t.s3p}</p></section><section className="legalSection"><h2>{t.s4}</h2><p>{t.s4p}</p></section><section className="legalSection"><h2>{t.s5}</h2><p>{t.s5p}</p></section><section className="legalSection"><h2>{t.s6}</h2><p>{t.s6p}</p></section><section className="legalSection"><h2>{t.contact}</h2><p>{t.contactP}</p></section>
  </main>;
}

export function generateStaticParams() {
  return [{ lang: 'fr' }, { lang: 'en' }, { lang: 'es' }];
}
