import { ArrowUpRight } from 'lucide-react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { isSiteLanguage, pageMetadata } from '../../../lib/seo';

const restaurant = {
  name: 'SAS NOMADE',
  address: '42 Rue des Chapeliers, 09000 Foix, France',
  contact: 'nomaderestaubar@gmail.com · 07 45 26 28 23',
};

const copy = {
  fr: { title:'Politique de confidentialité', description:'Politique de confidentialité des demandes de réservation de NOMADE à Foix.', back:'Retour au site', intro:'NOMADE traite les données personnelles nécessaires à la gestion des demandes de réservation et de contact, conformément au Règlement Général sur la Protection des Données (RGPD).', s1:'Responsable du traitement',s1p:`Le responsable du traitement est ${restaurant.name}, ${restaurant.address}.`,s2:'Données collectées, finalités et base juridique',s2p:'Le formulaire de réservation transmet votre nom, numéro de téléphone, date, heure et nombre de personnes. Le restaurant peut ensuite associer à la demande un statut de suivi et un commentaire interne. Ces données servent uniquement à traiter la demande, vérifier la disponibilité et vous recontacter. Le traitement repose sur les mesures précontractuelles prises à votre demande et, pour le suivi administratif, sur l’intérêt légitime du restaurant.',s3:'Destinataires, services utilisés et conservation',s3p:'La demande est transmise à la boîte e-mail du restaurant et enregistrée dans un tableau Google Sheets utilisé comme registre opérationnel des réservations. Ces services sont fournis par Google. L’accès est limité aux personnes autorisées par NOMADE. Les données sont conservées pendant la durée nécessaire au traitement et au suivi de la demande, puis supprimées ou anonymisées, sous réserve des obligations légales applicables. Les traitements réalisés par Google sont encadrés par ses engagements contractuels et garanties applicables en matière de protection des données.',s4:'Cookies et préférences',s4p:'Avec votre consentement, le site utilise Google Analytics pour mesurer l’audience, notamment les pages consultées, la provenance, le type d’appareil et les interactions agrégées. Vous pouvez accepter, refuser ou modifier ce choix à tout moment avec le lien « Gérer les cookies » situé dans le pied de page.',s5:'Vos droits',s5p:'Vous disposez notamment d’un droit d’accès, de rectification, d’effacement, de limitation, d’opposition et de portabilité de vos données. Pour exercer ces droits, contactez le restaurant aux coordonnées ci-dessous.',s6:'Réclamation',s6p:'Vous pouvez également introduire une réclamation auprès de la CNIL (www.cnil.fr) si vous estimez que vos droits ne sont pas respectés.',contact:'Contact'},
  en: { title:'Privacy policy', description:'Privacy policy for booking requests at NOMADE in Foix.', back:'Back to site', intro:'NOMADE processes the personal data needed to manage booking and contact requests in accordance with the General Data Protection Regulation (GDPR).', s1:'Data controller',s1p:`The data controller is ${restaurant.name}, ${restaurant.address}.`,s2:'Data collected, purposes and legal basis',s2p:'The booking form sends your name, phone number, date, time and number of guests. The restaurant may then add a follow-up status and an internal comment to the request. This information is used only to handle the request, check availability and contact you. Processing is based on steps taken at your request before entering into a contract and, for administrative follow-up, on the restaurant’s legitimate interests.',s3:'Recipients, services used and retention',s3p:'The request is delivered to the restaurant mailbox and recorded in a Google Sheets spreadsheet used as the operational booking register. These services are provided by Google. Access is limited to people authorised by NOMADE. Data is retained for the time needed to process and follow up the request, then deleted or anonymised, subject to applicable legal obligations. Processing by Google is governed by its applicable contractual data-protection commitments and safeguards.',s4:'Cookies and preferences',s4p:'With your consent, the site uses Google Analytics to measure audience, including viewed pages, traffic sources, device type and aggregated interactions. You can accept, refuse or change this choice at any time using the “Manage cookies” link in the footer.',s5:'Your rights',s5p:'You have the right to access, rectify, erase, restrict or object to processing of your data, and to data portability. To exercise these rights, contact the restaurant using the details below.',s6:'Complaints',s6p:'You may also lodge a complaint with the CNIL (www.cnil.fr) if you believe your rights are not being respected.',contact:'Contact'},
  es: { title:'Política de privacidad', description:'Política de privacidad de las solicitudes de reserva de NOMADE en Foix.', back:'Volver al sitio', intro:'NOMADE trata los datos personales necesarios para gestionar las solicitudes de reserva y contacto de conformidad con el Reglamento General de Protección de Datos (RGPD).', s1:'Responsable del tratamiento',s1p:`El responsable del tratamiento es ${restaurant.name}, ${restaurant.address}.`,s2:'Datos recopilados, finalidades y base jurídica',s2p:'El formulario de reserva envía su nombre, teléfono, fecha, hora y número de personas. El restaurante puede añadir después un estado de seguimiento y un comentario interno a la solicitud. Estos datos se utilizan únicamente para tramitar la solicitud, comprobar la disponibilidad y ponerse en contacto con usted. El tratamiento se basa en medidas precontractuales adoptadas a petición del interesado y, para el seguimiento administrativo, en el interés legítimo del restaurante.',s3:'Destinatarios, servicios utilizados y conservación',s3p:'La solicitud se envía al buzón del restaurante y se registra en una hoja de cálculo de Google Sheets utilizada como registro operativo de reservas. Estos servicios son prestados por Google. El acceso está limitado a las personas autorizadas por NOMADE. Los datos se conservan durante el tiempo necesario para tramitar y seguir la solicitud y, después, se eliminan o anonimizan, sin perjuicio de las obligaciones legales aplicables. El tratamiento realizado por Google se rige por sus compromisos contractuales y garantías aplicables en materia de protección de datos.',s4:'Cookies y preferencias',s4p:'Con su consentimiento, el sitio utiliza Google Analytics para medir la audiencia, incluidas las páginas vistas, las fuentes de tráfico, el tipo de dispositivo y las interacciones agregadas. Puede aceptar, rechazar o modificar esta elección en cualquier momento con el enlace « Gestionar cookies » situado en el pie de página.',s5:'Sus derechos',s5p:'Usted tiene derecho de acceso, rectificación, supresión, limitación u oposición al tratamiento de sus datos, así como a la portabilidad. Para ejercer estos derechos, contacte con el restaurante mediante los datos indicados a continuación.',s6:'Reclamaciones',s6p:'También puede presentar una reclamación ante la CNIL (www.cnil.fr) si considera que no se respetan sus derechos.',contact:'Contacto'}
};

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> {
  const { lang: rawLang } = await params;
  if (!isSiteLanguage(rawLang)) return {};
  const t = copy[rawLang];
  return pageMetadata(rawLang, '/confidentialite', `${t.title} | NOMADE — Foix`, t.description);
}

export default async function Confidentialite({ params }: { params: Promise<{ lang: string }> }) {
  const { lang: rawLang } = await params;
  const lang = (['fr', 'en', 'es'] as const).includes(rawLang as 'fr' | 'en' | 'es') ? rawLang as 'fr' | 'en' | 'es' : 'fr';
  const t = copy[lang];

  return <main className="legalPage" lang={lang}><div className="legalHead"><p className="eyebrow">NOMADE</p><h1>{t.title}</h1><Link className="textLink" href={`/${lang}#top`}>{t.back} <ArrowUpRight size={16} /></Link></div>
    <p className="lead legalIntro">{t.intro}</p>
    <section className="legalSection"><h2>{t.s1}</h2><p>{t.s1p}</p></section><section className="legalSection"><h2>{t.s2}</h2><p>{t.s2p}</p></section><section className="legalSection"><h2>{t.s3}</h2><p>{t.s3p}</p></section><section className="legalSection"><h2>{t.s4}</h2><p>{t.s4p}</p></section><section className="legalSection"><h2>{t.s5}</h2><p>{t.s5p}</p></section><section className="legalSection"><h2>{t.s6}</h2><p>{t.s6p}</p></section><section className="legalSection"><h2>{t.contact}</h2><p>{restaurant.contact}</p></section>
  </main>;
}

export function generateStaticParams() {
  return [{ lang: 'fr' }, { lang: 'en' }, { lang: 'es' }];
}
